# -*- coding: utf-8 -*-
"""2. Face Segmentation ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_nsEh3D6gP0WmwtkgqRtUgP9DtBpiYL

#SEGMENTATION WITH MODEL SAM 3

#Install transformers (RUN ONCE AND RESTART)
"""

!pip install -U transformers

"""## Local Inference on GPU
Model page: https://huggingface.co/facebook/sam3

⚠️ If the generated code snippets do not work, please open an issue on either the [model repo](https://huggingface.co/facebook/sam3)
			and/or on [huggingface.js](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/model-libraries-snippets.ts) 🙏

The model you are trying to use is gated. Please make sure you have access to it by visiting the model page.To run inference, either set HF_TOKEN in your environment variables/ Secrets or run the following cell to login. 🤗
"""

from huggingface_hub import login
login("hf_token")

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("mask-generation", model="facebook/sam3")

# Load model directly
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("facebook/sam3")
model = AutoModel.from_pretrained("facebook/sam3")

"""#Import model to segment image"""

from transformers import Sam3Processor, Sam3Model
import torch
from PIL import Image
import requests

device = "cuda" if torch.cuda.is_available() else "cpu"

model = Sam3Model.from_pretrained("facebook/sam3").to(device)
processor = Sam3Processor.from_pretrained("facebook/sam3")

"""#Import photos"""

# Load image
#image_url = "http://images.cocodataset.org/val2017/000000077595.jpg"
#image = Image.open(requests.get(image_url, stream=True).raw).convert("RGB")

from google.colab import files
from PIL import Image, ImageOps

print("="*70)
print("📸 Please upload an image file")
print("="*70)
uploaded = files.upload()

if len(uploaded) == 0:
    raise ValueError("No file uploaded! Please upload an image file.")

image_path = list(uploaded.keys())[0]
print(f"\n✓ File uploaded: {image_path}")

image = Image.open(image_path).convert("RGB")
# Apply EXIF orientation so the image is not upside down or sideways
image = ImageOps.exif_transpose(image)

w, h = image.size
if w > h:
    image = image.rotate(90, expand=True)
    print("✓ Image rotated to portrait orientation")

img = image

"""#Segmented masks

- Facial skin
- Eye brows
- Lips
- Nose
- Circular iris region of each eye
"""

# Segment using text prompts
prompts = [
    "skin of the face",
    "eyebrows",
    "lips",
    "nose",
    "circular iris region of each eye",
]

all_inputs = []
all_outputs = []

for text in prompts:
    inputs = processor(images=image, text=text, return_tensors="pt").to(device)
    with torch.no_grad():
        outputs = model(**inputs)
    all_inputs.append(inputs)
    all_outputs.append(outputs)

# Post-process results
selected_masks = []

for text, inputs, outputs in zip(prompts, all_inputs, all_outputs):
    results = processor.post_process_instance_segmentation(
        outputs,
        threshold=0.5,
        mask_threshold=0.5,
        target_sizes=inputs.get("original_sizes").tolist()
    )[0]

    print(f"Prompt '{text}': found {len(results['masks'])} objects")

    if len(results["masks"]) > 0:
        masks = results["masks"]     # [N, H, W]
        areas = masks.view(masks.shape[0], -1).sum(dim=1)
        best_idx = int(areas.argmax())
        selected_masks.append(masks[best_idx])

if len(selected_masks) > 0:
    stacked_masks = torch.stack(selected_masks)   # [num_prompts, H, W]
else:
    stacked_masks = None

import numpy as np
import matplotlib
from IPython.display import display

def overlay_masks(image, masks):
    image = image.convert("RGBA")
    masks = 255 * masks.cpu().numpy().astype(np.uint8)

    n_masks = masks.shape[0]
    cmap = matplotlib.colormaps.get_cmap("rainbow").resampled(n_masks)
    colors = [
        tuple(int(c * 255) for c in cmap(i)[:3])
        for i in range(n_masks)
    ]

    for mask, color in zip(masks, colors):
        mask = Image.fromarray(mask)
        overlay = Image.new("RGBA", image.size, color + (0,))
        alpha = mask.point(lambda v: int(v * 0.5))
        overlay.putalpha(alpha)
        image = Image.alpha_composite(image, overlay)
    return image

# Show overlay for all regions (face skin, brows, lips, nose, both irises)
if stacked_masks is not None:
    out = overlay_masks(image, stacked_masks)
    display(out)
else:
    print("No masks to show.")

"""#Full code to segment with SAM 3 meta + Get Region Hex

RGB image → BGR → LAB
→ extract masked pixels
→ filter bottom/top 10% luminance
→ K-means (k=3) in LAB space
→ pick dominant cluster by pixel count
→ mean RGB of that cluster → hex
"""

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, ImageOps
from IPython.display import display, HTML
import time
import base64
import io
import json
from transformers import Sam3Processor, Sam3Model
import torch
import matplotlib
import cv2
from sklearn.cluster import KMeans
from google.colab import files, output

# ============================================================================
# SETUP SAM3 MODEL
# ============================================================================
device = "cuda" if torch.cuda.is_available() else "cpu"
model = Sam3Model.from_pretrained("facebook/sam3").to(device)
processor = Sam3Processor.from_pretrained("facebook/sam3")

# ============================================================================
# LOAD AND PREPARE IMAGE
# ============================================================================
print("=" * 70)
print("📸 Please upload an image file")
print("=" * 70)
uploaded = files.upload()

if len(uploaded) == 0:
    raise ValueError("No file uploaded!")

image_path = list(uploaded.keys())[0]
image = Image.open(image_path).convert("RGB")
image = ImageOps.exif_transpose(image)
img = image
img_np = np.array(img)

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================
def rgb_to_hex(rgb):
    return f"#{int(rgb[0]):02X}{int(rgb[1]):02X}{int(rgb[2]):02X}"

def get_region_hex(image, mask_bool, n_clusters=3):
    """LAB K-means dominant color extraction."""
    img_np = np.array(image)
    img_h, img_w = img_np.shape[:2]

    if hasattr(mask_bool, "shape"):
        mask_h, mask_w = mask_bool.shape[:2]
        if mask_h != img_h or mask_w != img_w:
            mask_pil = Image.fromarray(mask_bool.astype(np.uint8) * 255)
            mask_resized = mask_pil.resize((img_w, img_h), Image.NEAREST)
            mask_bool = np.array(mask_resized).astype(bool)

    img_bgr = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)
    img_lab = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2LAB)

    pixels_lab = img_lab[mask_bool].astype(float)
    pixels_rgb = img_np[mask_bool].astype(float)

    if len(pixels_lab) == 0:
        return None, None

    L = pixels_lab[:, 0]
    low, high = np.percentile(L, 10), np.percentile(L, 90)
    valid = (L >= low) & (L <= high)
    pixels_lab = pixels_lab[valid]
    pixels_rgb = pixels_rgb[valid]

    if len(pixels_lab) < n_clusters:
        median_rgb = np.median(pixels_rgb, axis=0).astype(int)
        return median_rgb.tolist(), rgb_to_hex(median_rgb)

    k = min(n_clusters, len(pixels_lab))
    km = KMeans(n_clusters=k, n_init=10, random_state=42)
    km.fit(pixels_lab)
    counts = np.bincount(km.labels_)
    dominant_idx = counts.argmax()
    dominant_rgb = pixels_rgb[km.labels_ == dominant_idx]
    mean_rgb = dominant_rgb.mean(axis=0).astype(int)
    return mean_rgb.tolist(), rgb_to_hex(mean_rgb)

def pil_to_base64(pil_img, max_width=500):
    """Convert PIL image to base64 string for HTML embedding."""
    ratio = max_width / pil_img.width
    new_size = (max_width, int(pil_img.height * ratio))
    resized = pil_img.resize(new_size, Image.LANCZOS)
    buffered = io.BytesIO()
    resized.save(buffered, format="JPEG", quality=90)
    b64 = base64.b64encode(buffered.getvalue()).decode("utf-8")
    return b64, resized.size

def overlay_masks(image, masks):
    image = image.convert("RGBA")
    masks_np = 255 * masks.cpu().numpy().astype(np.uint8)
    n_masks = masks_np.shape[0]
    cmap = matplotlib.colormaps.get_cmap("rainbow").resampled(n_masks)
    colors = [tuple(int(c * 255) for c in cmap(i)[:3]) for i in range(n_masks)]
    for mask, color in zip(masks_np, colors):
        mask_img = Image.fromarray(mask)
        overlay = Image.new("RGBA", image.size, color + (0,))
        alpha = mask_img.point(lambda v: int(v * 0.5))
        overlay.putalpha(alpha)
        image = Image.alpha_composite(image, overlay)
    return image

def create_combined_visualization(original_image, segmentation_image, region_hex):
    names = [k for k, v in region_hex.items() if v is not None]
    n_cols = 3 + max(len(names), 1)
    fig, axes = plt.subplots(1, n_cols, figsize=(2 * n_cols, 5))
    if n_cols == 1:
        axes = [axes]

    axes[0].imshow(original_image)
    axes[0].set_title("Original Face", fontsize=10, fontweight="bold")
    axes[0].axis("off")
    axes[1].imshow(segmentation_image)
    axes[1].set_title("Segmentation", fontsize=10, fontweight="bold")
    axes[1].axis("off")
    axes[2].axis("off")

    text_content = "Region Colors\n" + "=" * 20 + "\n"
    for name in names:
        manual_tag = " (manual)" if region_hex[name].get("manual") else ""
        text_content += f"{name}:\n  RGB={region_hex[name]['avg_rgb']}\n  hex={region_hex[name]['hex']}{manual_tag}\n\n"
    axes[2].text(0.05, 0.95, text_content, transform=axes[2].transAxes,
                 fontsize=8, verticalalignment="top", family="monospace",
                 bbox=dict(boxstyle="round", facecolor="wheat", alpha=0.3))

    for idx, name in enumerate(names):
        ax = axes[3 + idx]
        rgb = np.array(region_hex[name]["avg_rgb"]) / 255.0
        swatch = np.ones((80, 80, 3), dtype=float)
        swatch[:] = rgb
        ax.imshow(swatch)
        ax.axis("off")
        manual_tag = " (manual)" if region_hex[name].get("manual") else ""
        ax.set_title(f"{name}\n{region_hex[name]['hex']}{manual_tag}", fontsize=8)

    plt.suptitle("Face Analysis Results", fontsize=12, fontweight="bold", y=1.02)
    plt.tight_layout()
    plt.show()

# ============================================================================
# HTML COLOR PICKER — eval_js Promise, no kernel blocking
# ============================================================================
def html_color_picker(img_pil, iris_key, initial_hex="#6496C8"):
    b64, (disp_w, disp_h) = pil_to_base64(img_pil, max_width=480)

    html_code = f"""
    <div style="font-family:monospace; max-width:700px;">
      <h3 style="margin-bottom:4px;">
        👁️ {iris_key.replace('_', ' ').title()} — Pick eye color
      </h3>
      <p style="margin:0 0 10px 0; font-size:12px; color:#666;">
        🖱️ Hover to preview &nbsp;|&nbsp;
        🖱️ Click to lock color &nbsp;|&nbsp;
        🖱️ Double-click to unlock &nbsp;|&nbsp;
        ✅ Press Confirm when ready
      </p>
      <div style="display:flex; gap:24px; align-items:flex-start;">

        <div style="position:relative; width:{disp_w}px; height:{disp_h}px;
                    cursor:crosshair; flex-shrink:0;">
          <img id="photo_{iris_key}"
               src="data:image/jpeg;base64,{b64}"
               width="{disp_w}" height="{disp_h}"
               style="display:block; position:absolute; top:0; left:0;
                      user-select:none; -webkit-user-drag:none;"/>
          <canvas id="canvas_{iris_key}"
                  width="{disp_w}" height="{disp_h}"
                  style="position:absolute; top:0; left:0;"></canvas>
        </div>

        <div style="display:flex; flex-direction:column; gap:12px; min-width:170px;">
          <div id="swatch_{iris_key}"
               style="width:130px; height:130px; border-radius:12px;
                      border:2px solid #ccc; background:{initial_hex};
                      transition: background 0.1s;"></div>
          <div id="hex_label_{iris_key}"
               style="font-size:22px; font-weight:bold; letter-spacing:1px;">
            {initial_hex}
          </div>
          <div id="rgb_label_{iris_key}" style="font-size:13px; color:#555;">
            RGB: hover over image
          </div>
          <div id="status_{iris_key}"
               style="font-size:12px; color:#888; min-height:18px;">
            Click image to lock a color
          </div>
          <button onclick="confirmColor_{iris_key}()"
                  style="margin-top:4px; padding:10px 18px; font-size:14px;
                         background:#2196F3; color:white; border:none;
                         border-radius:8px; cursor:pointer; font-weight:bold;">
            ✅ Confirm this color
          </button>
        </div>
      </div>
    </div>

    <script>
    (function() {{
      const canvas  = document.getElementById('canvas_{iris_key}');
      const ctx     = canvas.getContext('2d');
      const imgEl   = document.getElementById('photo_{iris_key}');
      const swatch  = document.getElementById('swatch_{iris_key}');
      const hexLbl  = document.getElementById('hex_label_{iris_key}');
      const rgbLbl  = document.getElementById('rgb_label_{iris_key}');
      const status  = document.getElementById('status_{iris_key}');

      const off = document.createElement('canvas');
      off.width = {disp_w}; off.height = {disp_h};
      const offCtx = off.getContext('2d');
      const drawOff = () => offCtx.drawImage(imgEl, 0, 0);
      if (imgEl.complete) drawOff(); else imgEl.onload = drawOff;

      let locked = false;

      function toHex(r, g, b) {{
        return '#' + [r,g,b].map(v =>
          v.toString(16).padStart(2,'0').toUpperCase()).join('');
      }}

      function getAvgColor(x, y, radius=8) {{
        const x1 = Math.max(0, x-radius), y1 = Math.max(0, y-radius);
        const x2 = Math.min({disp_w}, x+radius), y2 = Math.min({disp_h}, y+radius);
        const data = offCtx.getImageData(x1, y1, x2-x1, y2-y1).data;
        let r=0, g=0, b=0, n=0;
        for (let i=0; i<data.length; i+=4) {{
          r+=data[i]; g+=data[i+1]; b+=data[i+2]; n++;
        }}
        return [Math.round(r/n), Math.round(g/n), Math.round(b/n)];
      }}

      function drawCrosshair(x, y, color) {{
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        ctx.strokeStyle = color;
        ctx.lineWidth = 1.5;
        ctx.shadowColor = 'rgba(0,0,0,0.9)';
        ctx.shadowBlur = 4;
        ctx.beginPath(); ctx.moveTo(0,y); ctx.lineTo(canvas.width,y); ctx.stroke();
        ctx.beginPath(); ctx.moveTo(x,0); ctx.lineTo(x,canvas.height); ctx.stroke();
        ctx.beginPath(); ctx.arc(x, y, 7, 0, 2*Math.PI);
        ctx.lineWidth = 2; ctx.stroke();
      }}

      function updatePreview(hex, r, g, b) {{
        swatch.style.background = hex;
        hexLbl.textContent = hex;
        rgbLbl.textContent = `RGB: ${{r}}, ${{g}}, ${{b}}`;
      }}

      canvas.addEventListener('mousemove', function(e) {{
        if (locked) return;
        const rect = canvas.getBoundingClientRect();
        const x = Math.round(e.clientX - rect.left);
        const y = Math.round(e.clientY - rect.top);
        const [r,g,b] = getAvgColor(x, y);
        drawCrosshair(x, y, 'white');
        updatePreview(toHex(r,g,b), r, g, b);
      }});

      canvas.addEventListener('click', function(e) {{
        const rect = canvas.getBoundingClientRect();
        const x = Math.round(e.clientX - rect.left);
        const y = Math.round(e.clientY - rect.top);
        const [r,g,b] = getAvgColor(x, y);
        const hex = toHex(r,g,b);
        locked = true;
        drawCrosshair(x, y, '#2196F3');
        updatePreview(hex, r, g, b);
        swatch.style.border = '3px solid #2196F3';
        hexLbl.style.color = '#2196F3';
        hexLbl.textContent = hex + ' 🔒';
        status.textContent = '🔒 Locked! Double-click to re-pick.';
        status.style.color = '#2196F3';
        window['picked_{iris_key}'] = {{ hex, r, g, b }};
      }});

      canvas.addEventListener('dblclick', function(e) {{
        locked = false;
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        swatch.style.border = '2px solid #ccc';
        hexLbl.style.color = 'black';
        hexLbl.textContent = hexLbl.textContent.replace(' 🔒','');
        status.textContent = 'Click image to lock a color';
        status.style.color = '#888';
      }});

      window['confirmColor_{iris_key}'] = function() {{
        const p = window['picked_{iris_key}'];
        if (!p) {{
          alert('Please click on the image first!');
          return;
        }}
        window['result_{iris_key}'] = JSON.stringify(p);
        hexLbl.textContent = '✅ ' + p.hex;
        hexLbl.style.color = 'green';
        status.textContent = '✅ Color confirmed!';
        status.style.color = 'green';
        swatch.style.border = '3px solid green';
      }};
    }})();
    </script>
    """

    display(HTML(html_code))

    print(f"\n⏳ Waiting for you to pick and confirm the {iris_key} color...")
    print("   Hover → preview | Click → lock 🔒 | Double-click → unlock | ✅ Confirm")

    result_json = output.eval_js(f"""
      new Promise((resolve) => {{
        const interval = setInterval(() => {{
          if (window['result_{iris_key}']) {{
            clearInterval(interval);
            resolve(window['result_{iris_key}']);
          }}
        }}, 500);
      }})
    """)

    result = json.loads(result_json)
    rgb = [result["r"], result["g"], result["b"]]
    hex_color = result["hex"]
    print(f"✓ Received: {hex_color} RGB={rgb}")
    return rgb, hex_color

# ============================================================================
# SAM3 PROMPTS — no iris, handled by picker
# ============================================================================
prompts = [
    "skin of the face",
    "eyebrows",
    "lips",
    "nose",
]

prompt_keys = {
    "skin of the face": "face_skin",
    "eyebrows": "eyebrows",
    "lips": "lips",
    "nose": "nose",
}

all_inputs, all_outputs = [], []
for text in prompts:
    inputs = processor(images=image, text=text, return_tensors="pt").to(device)
    with torch.no_grad():
        outputs = model(**inputs)
    all_inputs.append(inputs)
    all_outputs.append(outputs)

# ============================================================================
# POST-PROCESS MASKS
# ============================================================================
selected_masks = []
for text, inputs, outputs in zip(prompts, all_inputs, all_outputs):
    results = processor.post_process_instance_segmentation(
        outputs, threshold=0.5, mask_threshold=0.5,
        target_sizes=inputs.get("original_sizes").tolist(),
    )[0]
    print(f"Prompt '{text}': found {len(results['masks'])} objects")
    if len(results["masks"]) > 0:
        masks = results["masks"]
        areas = masks.view(masks.shape[0], -1).sum(dim=1)
        selected_masks.append(masks[int(areas.argmax())])
    else:
        selected_masks.append(None)

region_masks = {}
for text, mask in zip(prompts, selected_masks):
    key = prompt_keys[text]
    region_masks[key] = mask.bool() if mask is not None else None

# ============================================================================
# SEGMENTATION OVERLAY
# ============================================================================
valid_masks = [m for m in selected_masks if m is not None]
segmentation_image = overlay_masks(image, torch.stack(valid_masks)) if valid_masks else image

# ============================================================================
# EXTRACT HEX COLORS WITH LAB K-MEANS (non-iris regions only)
# ============================================================================
region_hex = {}
for name, mask in region_masks.items():
    if mask is None:
        region_hex[name] = None
        continue
    mask_bool = mask.cpu().numpy().astype(bool) if hasattr(mask, "cpu") else mask.astype(bool)
    avg_rgb, hex_col = get_region_hex(img, mask_bool, n_clusters=3)
    region_hex[name] = {"avg_rgb": avg_rgb, "hex": hex_col, "manual": False} if avg_rgb is not None else None

# ============================================================================
# EYE COLOR — always use HTML picker, ask if both eyes same color
# ============================================================================
print(f"\n{'='*70}")
print(f"👁️  Left Iris — click on the eye in the photo")
print(f"{'='*70}")
picked_rgb_left, picked_hex_left = html_color_picker(img, "left_iris", initial_hex="#6496C8")
region_hex["left_iris"] = {"avg_rgb": picked_rgb_left, "hex": picked_hex_left, "manual": True}
print(f"✓ left_iris set to {picked_hex_left}")

same_color = input("\n👀 Do both eyes have the same color? (y/n): ").strip().lower()

if same_color == "y":
    region_hex["right_iris"] = {"avg_rgb": picked_rgb_left, "hex": picked_hex_left, "manual": True}
    print(f"✓ right_iris set to same color: {picked_hex_left}")
else:
    print(f"\n{'='*70}")
    print(f"👁️  Right Iris — click on the eye in the photo")
    print(f"{'='*70}")
    picked_rgb_right, picked_hex_right = html_color_picker(img, "right_iris", initial_hex="#6496C8")
    region_hex["right_iris"] = {"avg_rgb": picked_rgb_right, "hex": picked_hex_right, "manual": True}
    print(f"✓ right_iris set to {picked_hex_right}")

# ============================================================================
# FINAL OUTPUT
# ============================================================================
print("\n" + "=" * 70)
print("Region colors for this image:")
print("=" * 70)
for name, info in region_hex.items():
    if info is None:
        print(f"  {name}: no pixels")
    else:
        manual_tag = " (manual)" if info.get("manual") else ""
        print(f"  {name}: RGB={info['avg_rgb']}, hex={info['hex']}{manual_tag}")

create_combined_visualization(img, segmentation_image, region_hex)
