# -*- coding: utf-8 -*-
"""6. Recommender Gradio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MmAz2VYE5LuhtYGMV66rnVYiK57ZZvBX

# Makeup Recommender — Gradio App (Colab)

**Full pipeline in one notebook:**
1. Upload `products_catalog.csv` and `makeup_classifier.pth`
2. Install dependencies
3. Load models (SAM3 + ResNet-18)
4. Launch Gradio UI

The UI lets you:
- Upload a photo → auto-detect skin/lip/eye colors + classify look
- Or enter hex values manually
- Choose desired look + product types
- Get ranked recommendations with color swatches

## 1. Install dependencies
"""

!pip install gradio colormath scikit-learn pandas numpy Pillow torch torchvision transformers huggingface_hub -q
print('✅ Done')

"""## 2. Upload your files"""

from google.colab import files
import os

print('Upload products_catalog.csv')
uploaded = files.upload()
CATALOG_PATH = list(uploaded.keys())[0]
print(f'✅ Catalog: {CATALOG_PATH}')

print('Upload makeup_classifier.pth (from notebook 5)')
uploaded2 = files.upload()
MODEL_PATH = list(uploaded2.keys())[0]
print(f'✅ Model: {MODEL_PATH}')

"""## 3. Config & constants"""

import ast, json, warnings
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from PIL import Image, ImageDraw
from torchvision import models, transforms
from colormath.color_objects import sRGBColor, LabColor
from colormath.color_conversions import convert_color
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans
warnings.filterwarnings('ignore')

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {DEVICE}')

CATEGORIES = ['clean_makeup', 'festival_makeup', 'glam_makeup', 'no_makeup']
LOOK_LABELS  = {'no_makeup':'No Makeup','clean_makeup':'Clean / Natural','glam_makeup':'Glam','festival_makeup':'Festival'}

PRODUCT_TYPES = ['foundation','lipstick','blush','mascara','bronzer','eyeshadow','eyeliner','eyebrow','lip_liner']
TYPE_LABELS   = {'foundation':'Foundation','lipstick':'Lipstick','blush':'Blush','mascara':'Mascara',
                 'bronzer':'Bronzer','eyeshadow':'Eyeshadow','eyeliner':'Eyeliner','eyebrow':'Eyebrow','lip_liner':'Lip Liner'}

LIP_TYPES   = {'lipstick','lip_liner'}
EYE_TYPES   = {'eyeshadow','eyeliner','mascara','eyebrow'}
FACE_TYPES  = {'foundation','blush','bronzer'}

MONK_HEX    = ['f6ede4','f3e7db','f7ead0','eadaba','d7bd96','a07850','825c43','604134','3a312a','292420']
MONK_LABELS = ['Very Fair','Fair','Light','Light Medium','Medium','Tan','Deep Tan','Deep','Very Deep','Deepest']
MONK_RGB    = np.array([[int(h[i:i+2],16) for i in (0,2,4)] for h in MONK_HEX])

W_COLOR, W_CONTENT, W_STYLE = 0.45, 0.30, 0.25

STYLE_QUERIES = {
    'no_makeup':       'natural skin tinted lightweight sheer concealer nude minimal clean fresh glowy hydrating',
    'clean_makeup':    'dewy glowy skin foundation lightweight natural blush mascara neutral nude lip radiant',
    'glam_makeup':     'bold full-coverage contour highlight bronzer dramatic smoky eyeshadow liner pigmented lipstick long-wear',
    'festival_makeup': 'glitter shimmer holographic rhinestone neon bold colorful metallic eyeshadow graphic liner creative vibrant',
}

STYLE_BOOSTS = {
    'no_makeup':       {'foundation':1.2,'blush':1.1,'mascara':1.1,'lipstick':0.8,'eyeshadow':0.7,'eyeliner':0.6},
    'clean_makeup':    {'foundation':1.3,'blush':1.4,'mascara':1.2,'lipstick':1.1,'eyeshadow':0.9,'eyeliner':0.8},
    'glam_makeup':     {'eyeshadow':1.5,'eyeliner':1.4,'mascara':1.3,'lipstick':1.5,'bronzer':1.3,'foundation':1.2},
    'festival_makeup': {'eyeshadow':1.6,'eyeliner':1.5,'lipstick':1.4,'mascara':1.2,'bronzer':1.1},
}

print('✅ Config ready')

"""## 4. Load catalog + TF-IDF"""

df_catalog = pd.read_csv(CATALOG_PATH)
print(f'Catalog: {df_catalog.shape[0]} products')
print(df_catalog['product_type'].value_counts().to_string())

def parse_tags(t):
    try: return ' '.join(str(x) for x in ast.literal_eval(str(t)))
    except: return ''

df_catalog['content_doc'] = (
    df_catalog['description'].fillna('') + ' ' +
    df_catalog['product_type'].fillna('') + ' ' +
    df_catalog['category'].fillna('') + ' ' +
    df_catalog['brand'].fillna('') + ' ' +
    df_catalog['tag_list'].apply(parse_tags) + ' ' +
    df_catalog['undertone'].fillna('')
)

all_queries = list(STYLE_QUERIES.values())
corpus = df_catalog['content_doc'].tolist() + all_queries

tfidf = TfidfVectorizer(ngram_range=(1,2), max_features=8000, sublinear_tf=True, min_df=2)
tfidf_matrix = tfidf.fit_transform(corpus)
product_tfidf = tfidf_matrix[:len(df_catalog)]

print('✅ TF-IDF ready')

"""## 5. Load ResNet-18 classifier"""

checkpoint = torch.load(MODEL_PATH, map_location=DEVICE)

# Unpack checkpoint dict saved by notebook 5
if isinstance(checkpoint, dict) and "model_state_dict" in checkpoint:
    state_dict = checkpoint["model_state_dict"]
    saved_classes = checkpoint.get("classes", CATEGORIES)
    print(f"Checkpoint classes: {saved_classes}")
else:
    state_dict = checkpoint  # raw state_dict fallback

# Rebuild fc to match notebook 5: nn.Sequential(Dropout(0.3), Linear(512, 4))
resnet = models.resnet18(weights=None)
resnet.fc = nn.Sequential(
    nn.Dropout(0.3),
    nn.Linear(resnet.fc.in_features, len(CATEGORIES))
)

resnet.load_state_dict(state_dict)
resnet.eval().to(DEVICE)

resnet_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225]),
])

def classify_look(pil_img):
    tensor = resnet_transforms(pil_img.convert("RGB")).unsqueeze(0).to(DEVICE)
    with torch.no_grad():
        idx = resnet(tensor).argmax(1).item()
    return CATEGORIES[idx]

print(f"✅ ResNet-18 loaded. FC: {resnet.fc}")

"""## 6. Load SAM3 (needs HF token)


"""

USE_SAM = True

from huggingface_hub import login
from transformers import Sam3Processor, Sam3Model

login("hf_TOKEN")

sam_processor = Sam3Processor.from_pretrained("facebook/sam3")
sam_model     = Sam3Model.from_pretrained("facebook/sam3").to(DEVICE)
print("✅ SAM3 loaded")

"""## 7. Color & segmentation helpers"""

# ── LAB helpers ────────────────────────────────────────────────────────────
def hex_to_lab(hex_str):
    hex_str = str(hex_str).strip().lstrip('#')
    if len(hex_str) != 6: return np.array([50.,0.,0.])
    r,g,b = int(hex_str[0:2],16)/255, int(hex_str[2:4],16)/255, int(hex_str[4:6],16)/255
    lab = convert_color(sRGBColor(r,g,b), LabColor)
    return np.array([lab.lab_l, lab.lab_a, lab.lab_b])

def delta_e(h1, h2):
    return float(np.sqrt(np.sum((hex_to_lab(h1) - hex_to_lab(h2))**2)))

def de_score(de, max_de=100):
    return max(0., 1. - de/max_de)

def rgb_to_hex(r,g,b):
    return f'{int(np.clip(r,0,255)):02X}{int(np.clip(g,0,255)):02X}{int(np.clip(b,0,255)):02X}'

def dominant_hex(pixels, k=3):
    """K-means in LAB space → dominant cluster hex."""
    if len(pixels) < k: k = max(1, len(pixels))
    labs = []
    for p in pixels.astype(np.float32)/255:
        lab = convert_color(sRGBColor(*p[:3]), LabColor)
        labs.append([lab.lab_l, lab.lab_a, lab.lab_b])
    labs = np.array(labs)
    km = KMeans(n_clusters=k, n_init=5, random_state=42).fit(labs)
    ci = np.argmax(np.bincount(km.labels_))
    L,a,b = km.cluster_centers_[ci]
    rgb = convert_color(LabColor(L,a,b), sRGBColor)
    return rgb_to_hex(rgb.rgb_r*255, rgb.rgb_g*255, rgb.rgb_b*255)

def hex_to_monk(hex_str):
    hex_str = str(hex_str).strip().lstrip('#')
    rgb = np.array([int(hex_str[i:i+2],16) for i in (0,2,4)])
    return int(np.argmin(np.sqrt(np.sum((MONK_RGB-rgb)**2, axis=1)))) + 1

# ── Segmentation ──────────────────────────────────────────────────────────
PROMPTS = {
    'skin':   'skin of the face',
    'lips':   'lips',
    'eyes':   'circular iris region of each eye',
    'brows':  'eyebrows',
    'nose':   'nose',
}

def segment_sam(pil_img):
    """Run SAM3 segmentation. Returns dict of region→hex."""
    arr = np.array(pil_img.convert('RGB'))
    result = {}
    overlay = pil_img.convert('RGBA').copy()
    draw = ImageDraw.Draw(overlay)
    COLORS = {'skin':(255,180,180,120),'lips':(255,50,150,160),
              'eyes':(50,180,255,140),'brows':(150,80,200,140),'nose':(255,160,50,130)}

    for key, prompt in PROMPTS.items():
        inputs = sam_processor(images=pil_img, text=prompt, return_tensors='pt').to(DEVICE)
        with torch.no_grad():
            outputs = sam_model(**inputs)
        masks = sam_processor.post_process_instance_segmentation(
            outputs, threshold=0.5, mask_threshold=0.5,
            target_sizes=inputs['original_sizes'].tolist()
        )[0]['masks']

        if len(masks) == 0:
            result[key] = None
            continue

        mask = masks[0].cpu().numpy().astype(bool)
        pixels = arr[mask]
        lum = pixels.mean(axis=1)
        p10,p90 = np.percentile(lum,10), np.percentile(lum,90)
        pixels = pixels[(lum>=p10)&(lum<=p90)]
        result[key] = dominant_hex(pixels) if len(pixels) > 0 else None

        # Draw overlay
        color = COLORS.get(key,(200,200,200,100))
        mask_img = Image.fromarray((mask*255).astype(np.uint8))
        color_layer = Image.new('RGBA', pil_img.size, color)
        overlay.paste(color_layer, mask=mask_img)

    return result, overlay.convert('RGB')

def segment_crop(pil_img):
    """Crop-based fallback. Returns dict of region→hex."""
    arr = np.array(pil_img.convert('RGB'))
    H, W = arr.shape[:2]

    def crop_hex(r1,c1,r2,c2):
        region = arr[int(H*r1):int(H*r2), int(W*c1):int(W*c2)].reshape(-1,3)
        return dominant_hex(region) if len(region) > 0 else 'C8A07A'

    result = {
        'skin':  crop_hex(0.15, 0.25, 0.55, 0.75),
        'lips':  crop_hex(0.62, 0.35, 0.78, 0.65),
        'eyes':  crop_hex(0.30, 0.15, 0.50, 0.85),
        'brows': crop_hex(0.25, 0.20, 0.38, 0.80),
        'nose':  crop_hex(0.45, 0.38, 0.62, 0.62),
    }

    # Draw a simple annotation overlay
    overlay = pil_img.copy().convert('RGB')
    draw = ImageDraw.Draw(overlay)
    BOXES = [
        (0.15,0.25,0.55,0.75,(200,150,150),'skin'),
        (0.62,0.35,0.78,0.65,(200,80,120),'lips'),
        (0.30,0.15,0.50,0.85,(80,150,200),'eyes'),
    ]
    for r1,c1,r2,c2,color,label in BOXES:
        draw.rectangle([int(W*c1),int(H*r1),int(W*c2),int(H*r2)], outline=color, width=2)

    return result, overlay

def analyze_image(pil_img):
    """Full analysis: segmentation + ResNet classification."""
    if sam_model is not None:
        regions, overlay = segment_sam(pil_img)
        method = 'SAM3'
    else:
        regions, overlay = segment_crop(pil_img)
        method = 'Crop fallback'

    look = classify_look(pil_img)
    skin_hex = regions.get('skin') or 'C8A07A'
    monk = hex_to_monk(skin_hex)

    return {
        'regions':   regions,
        'overlay':   overlay,
        'look':      look,
        'skin_hex':  skin_hex,
        'lip_hex':   regions.get('lips') or 'A05450',
        'eye_hex':   regions.get('eyes') or '4D453B',
        'monk':      monk,
        'undertone': 'warm' if monk <= 5 else 'cool',
        'method':    method,
    }

print('✅ Segmentation helpers ready')

"""## 8. Recommender engine"""

def minmax(arr):
    mn, mx = arr.min(), arr.max()
    return np.ones(len(arr)) if mx==mn else (arr-mn)/(mx-mn)

def get_target_hex(product_type, skin_hex, lip_hex, eye_hex):
    pt = str(product_type).lower()
    if pt in LIP_TYPES:  return lip_hex
    if pt in EYE_TYPES:  return eye_hex
    if pt in FACE_TYPES: return skin_hex
    return skin_hex

def best_shade(row, target_hex):
    """Return (best_shade_hex, best_delta_e_score) for a product row."""
    try: colors = ast.literal_eval(row['product_colors'])
    except: return 'CCBBAA', 0.0
    best_h, best_s = 'CCBBAA', 0.0
    for c in colors:
        try:
            h = c['hex_value'].lstrip('#')
            s = de_score(delta_e(h, target_hex))
            if s > best_s: best_h, best_s = h, s
        except: continue
    return best_h, best_s

def run_recommender(
    skin_hex, lip_hex, eye_hex,
    desired_look, selected_types,
    undertone=None, monk_level=None,
    price_min=None, price_max=None,
    top_k=12
):
    df = df_catalog.copy()

    # ── Filter: product type ──
    if selected_types:
        df = df[df['product_type'].isin(selected_types)]

    if df.empty:
        return pd.DataFrame()

    # ── Filter: price ──
    if price_min is not None and price_min > 0:
        df = df[df['price'] >= price_min]
    if price_max is not None and price_max > 0:
        df = df[df['price'] <= price_max]

    # ── Filter: undertone (face products only) ──
    if undertone and undertone != 'any':
        face_mask = df['product_type'].isin(FACE_TYPES)
        ut_ok     = df['undertone'].str.lower() == undertone.lower()
        neut_ok   = df['undertone'].str.lower() == 'neutral'
        df = df[(~face_mask) | ut_ok | neut_ok]

    if df.empty:
        return pd.DataFrame()

    # ── Signal 1: color score ──
    color_scores, shade_hexes = [], []
    for _, row in df.iterrows():
        target = get_target_hex(row['product_type'], skin_hex, lip_hex, eye_hex)
        h, s   = best_shade(row, target)
        color_scores.append(s)
        shade_hexes.append(h)
    df = df.copy()
    df['color_score'] = color_scores
    df['best_shade']  = shade_hexes

    # ── Signal 2: content score ──
    query_vec     = tfidf.transform([STYLE_QUERIES.get(desired_look, '')])
    # Re-index product_tfidf to match filtered df
    idx_in_orig   = df.index.tolist()
    prod_vecs     = product_tfidf[idx_in_orig]
    df['content_score'] = cosine_similarity(query_vec, prod_vecs).flatten()

    # ── Signal 3: style score ──
    boosts = STYLE_BOOSTS.get(desired_look, {})
    df['style_mult']  = df['product_type'].apply(lambda pt: boosts.get(str(pt).lower(), 1.0))

    # ── Normalise & combine ──
    df['cn'] = minmax(df['color_score'].values)
    df['tn'] = minmax(df['content_score'].values)
    df['sn'] = minmax(df['style_mult'].values)

    df['hybrid'] = W_COLOR*df['cn'] + W_CONTENT*df['tn'] + W_STYLE*df['sn']

    top = (
        df.sort_values('hybrid', ascending=False)
          .drop_duplicates(subset='id')
          .head(top_k)
          .reset_index(drop=True)
    )
    return top

print('✅ Recommender engine ready')

"""## 9. Swatch image builder (for Gradio gallery)"""

from PIL import ImageFont
import io

def hex_to_rgb(h):
    h = str(h).strip().lstrip('#')
    if len(h) != 6: return (200,180,160)
    return tuple(int(h[i:i+2],16) for i in (0,2,4))

def make_swatch_card(row, rank):
    """Create a small PIL image card for one recommendation."""
    W, H = 300, 130
    shade_rgb = hex_to_rgb(row.get('best_shade','CCBBAA'))
    bg = (250,248,244)
    img = Image.new('RGB', (W,H), bg)
    draw = ImageDraw.Draw(img)

    # Color strip at top
    draw.rectangle([0,0,W,8], fill=shade_rgb)

    # Swatch circle
    draw.ellipse([16,18,64,66], fill=shade_rgb, outline=(220,210,200), width=1)

    # Rank badge
    draw.ellipse([14,16,30,32], fill=(139,105,20))
    try: font_sm = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf', 9)
    except: font_sm = ImageFont.load_default()
    draw.text((22,24), str(rank), fill='white', font=font_sm, anchor='mm')

    # Text
    try:
        font_bold = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf', 11)
        font_reg  = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf', 10)
        font_sm2  = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf', 9)
    except:
        font_bold = font_reg = font_sm2 = ImageFont.load_default()

    brand = str(row.get('brand','')).title()
    name  = str(row.get('name',''))
    if len(name) > 28: name = name[:26]+'...'
    ptype = TYPE_LABELS.get(str(row.get('product_type','')), str(row.get('product_type','')))
    price = f"{row.get('price_sign','$')}{row.get('price',0):.0f} {row.get('currency','')}"
    score = f"{row.get('hybrid',0)*100:.0f}% match"

    draw.text((76, 22), ptype, fill=(154,136,128), font=font_sm2)
    draw.text((76, 35), brand, fill=(92,79,69), font=font_reg)
    draw.text((76, 50), name,  fill=(28,22,18), font=font_bold)
    draw.text((76, 68), price, fill=(92,79,69), font=font_reg)

    # Score bar
    bar_x, bar_y, bar_w = 16, 90, W-32
    draw.rectangle([bar_x, bar_y, bar_x+bar_w, bar_y+5], fill=(225,218,210))
    fill_w = int(bar_w * row.get('hybrid',0))
    draw.rectangle([bar_x, bar_y, bar_x+fill_w, bar_y+5], fill=(139,105,20))
    draw.text((bar_x+bar_w+4, bar_y-1), score, fill=(154,136,128), font=font_sm2)

    # Separator
    draw.rectangle([0,H-1,W,H], fill=(225,218,210))

    return img

def make_results_image(top_df):
    """Stack all swatch cards into one tall image."""
    if top_df.empty:
        img = Image.new('RGB', (300,100), (250,248,244))
        draw = ImageDraw.Draw(img)
        draw.text((20,40), 'No results found.', fill=(154,136,128))
        return img

    cards = [make_swatch_card(row, i+1) for i, (_,row) in enumerate(top_df.iterrows())]
    cols = 2
    rows = (len(cards)+1)//2
    W, H = 300, 130
    gap = 8
    total_w = cols*W + (cols-1)*gap
    total_h = rows*H + (rows-1)*gap
    canvas = Image.new('RGB', (total_w, total_h), (242,237,232))
    for i, card in enumerate(cards):
        r, c = divmod(i, cols)
        canvas.paste(card, (c*(W+gap), r*(H+gap)))
    return canvas

print('✅ Swatch builder ready')

"""## 10. Gradio UI — Launch"""

import gradio as gr
import pandas as pd
import tempfile

_analysis = {}

def make_swatch(h, fallback):
    h = str(h).strip().lstrip('#')
    if len(h) != 6:
        h = fallback
    return f'<div style="width:52px;height:52px;border-radius:50%;background:#{h};border:2px solid #E0D8D0;flex-shrink:0;margin-top:8px"></div>'

def run_analysis(photo):
    if photo is None:
        return (None,
                '<p style="color:#9A8880;font-style:italic">Upload a photo and click Analyze.</p>',
                '', '', '', '', 4, '')

    pil_img = Image.fromarray(photo).convert('RGB')
    result  = analyze_image(pil_img)
    _analysis.update(result)

    skin_hex = result['skin_hex']
    lip_hex  = result['lip_hex']
    eye_hex  = result['eye_hex']
    brow_hex = result['regions'].get('brows') or 'A08060'
    nose_hex = result['regions'].get('nose')  or 'C09080'
    monk     = result['monk']
    look     = result['look']

    info_html = (
        '<div style="font-family:Georgia,serif;padding:16px 0">'
        '<div style="display:flex;gap:16px;align-items:flex-start;flex-wrap:wrap;margin-bottom:20px">'
        f'<div style="text-align:center"><div style="width:48px;height:48px;border-radius:50%;background:#{skin_hex};border:2px solid #E0D8D0;margin-bottom:4px"></div><div style="font-size:11px;color:#9A8880">Face skin</div></div>'
        f'<div style="text-align:center"><div style="width:48px;height:48px;border-radius:50%;background:#{lip_hex};border:2px solid #E0D8D0;margin-bottom:4px"></div><div style="font-size:11px;color:#9A8880">Lips</div></div>'
        f'<div style="text-align:center"><div style="width:48px;height:48px;border-radius:50%;background:#{eye_hex};border:2px solid #E0D8D0;margin-bottom:4px"></div><div style="font-size:11px;color:#9A8880">Eyes</div></div>'
        f'<div style="text-align:center"><div style="width:48px;height:48px;border-radius:50%;background:#{brow_hex};border:2px solid #E0D8D0;margin-bottom:4px"></div><div style="font-size:11px;color:#9A8880">Eyebrows</div></div>'
        f'<div style="text-align:center"><div style="width:48px;height:48px;border-radius:50%;background:#{nose_hex};border:2px solid #E0D8D0;margin-bottom:4px"></div><div style="font-size:11px;color:#9A8880">Nose</div></div>'
        '</div>'
        '<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">'
        '<div style="background:#F5F0EB;border-radius:10px;padding:12px">'
        '<div style="font-size:11px;color:#9A8880;letter-spacing:.06em;text-transform:uppercase;margin-bottom:4px">Detected look</div>'
        f'<div style="font-size:15px;font-weight:500;color:#3D2B2B">{LOOK_LABELS[look]}</div>'
        '</div>'
        '<div style="background:#F5F0EB;border-radius:10px;padding:12px">'
        '<div style="font-size:11px;color:#9A8880;letter-spacing:.06em;text-transform:uppercase;margin-bottom:4px">Monk level</div>'
        '<div style="display:flex;align-items:center;gap:8px">'
        f'<div style="width:24px;height:24px;border-radius:50%;background:#{MONK_HEX[monk-1]};border:1px solid #ddd"></div>'
        f'<span style="font-size:15px;font-weight:500;color:#3D2B2B">{monk} — {MONK_LABELS[monk-1]}</span>'
        '</div></div>'
        '<div style="background:#F5F0EB;border-radius:10px;padding:12px">'
        '<div style="font-size:11px;color:#9A8880;letter-spacing:.06em;text-transform:uppercase;margin-bottom:4px">Undertone</div>'
        f'<div style="font-size:15px;font-weight:500;color:#3D2B2B;text-transform:capitalize">{result["undertone"]}</div>'
        '</div>'
        '<div style="background:#F5F0EB;border-radius:10px;padding:12px">'
        '<div style="font-size:11px;color:#9A8880;letter-spacing:.06em;text-transform:uppercase;margin-bottom:4px">Method</div>'
        f'<div style="font-size:15px;font-weight:500;color:#3D2B2B">{result["method"]}</div>'
        '</div></div>'
        '</div>'
    )

    return (result['overlay'], info_html,
            skin_hex, lip_hex, eye_hex, look, monk, '')


def run_recommend(
    skin_hex, lip_hex, eye_hex, look_label, types, ut, monk,
    pmin_foundation, pmax_foundation,
    pmin_lipstick,   pmax_lipstick,
    pmin_blush,      pmax_blush,
    pmin_mascara,    pmax_mascara,
    pmin_bronzer,    pmax_bronzer,
    pmin_eyeshadow,  pmax_eyeshadow,
    pmin_eyeliner,   pmax_eyeliner,
    pmin_eyebrow,    pmax_eyebrow,
    pmin_lip_liner,  pmax_lip_liner,
    n_foundation, n_lipstick, n_blush, n_mascara, n_bronzer,
    n_eyeshadow, n_eyeliner, n_eyebrow, n_lip_liner,
):
    if not types:
        return '<p style="color:#C4836A">⚠ Select at least one product type.</p>', gr.update(visible=False)

    label_to_key = {v: k for k, v in LOOK_LABELS.items()}
    look_key     = label_to_key.get(look_label, 'glam_makeup')

    n_map = {
        'foundation': int(n_foundation), 'lipstick': int(n_lipstick),
        'blush':      int(n_blush),      'mascara':  int(n_mascara),
        'bronzer':    int(n_bronzer),    'eyeshadow':int(n_eyeshadow),
        'eyeliner':   int(n_eyeliner),   'eyebrow':  int(n_eyebrow),
        'lip_liner':  int(n_lip_liner),
    }
    price_map = {
        'foundation': (pmin_foundation, pmax_foundation),
        'lipstick':   (pmin_lipstick,   pmax_lipstick),
        'blush':      (pmin_blush,      pmax_blush),
        'mascara':    (pmin_mascara,    pmax_mascara),
        'bronzer':    (pmin_bronzer,    pmax_bronzer),
        'eyeshadow':  (pmin_eyeshadow,  pmax_eyeshadow),
        'eyeliner':   (pmin_eyeliner,   pmax_eyeliner),
        'eyebrow':    (pmin_eyebrow,    pmax_eyebrow),
        'lip_liner':  (pmin_lip_liner,  pmax_lip_liner),
    }

    skin_hex = str(skin_hex).strip().lstrip('#') or 'C8A07A'
    lip_hex  = str(lip_hex).strip().lstrip('#')  or 'A05450'
    eye_hex  = str(eye_hex).strip().lstrip('#')  or '4D453B'

    all_results = []
    for type_label in types:
        type_key = next((k for k, v in TYPE_LABELS.items() if v == type_label), None)
        if not type_key:
            continue
        pmin, pmax = price_map.get(type_key, (0, 0))
        n_want     = n_map.get(type_key, 3)

        top = run_recommender(
            skin_hex, lip_hex, eye_hex,
            look_key, [type_key],
            undertone=ut if ut != 'Any' else None,
            monk_level=int(monk) if monk else 4,
            price_min=float(pmin) if pmin and pmin > 0 else None,
            price_max=float(pmax) if pmax and pmax > 0 else None,
            top_k=n_want,
        )
        all_results.append((type_label, top))

    if not any(not top.empty for _, top in all_results):
        return '<p style="color:#C4836A">❌ No products found. Try relaxing your filters.</p>', gr.update(visible=False)

    all_rows = []
    for _, top in all_results:
        for _, row in top.iterrows():
            all_rows.append(row)
    combined_df = pd.DataFrame(all_rows).reset_index(drop=True)

    lines = ['<div style="font-family:Georgia,serif;padding:8px 0">']
    rank  = 1
    for type_label, top in all_results:
        if top.empty:
            continue
        lines.append(
            f'<div style="font-size:11px;color:#9A8880;letter-spacing:.08em;text-transform:uppercase;'
            f'margin:16px 0 8px;border-bottom:1px solid #F0E8E0;padding-bottom:6px">{type_label}</div>'
        )
        for _, row in top.iterrows():
            shade    = str(row.get('best_shade', 'CCBBAA'))
            brand    = str(row.get('brand', '')).title()
            name     = str(row.get('name', ''))
            price    = f"{row.get('price_sign','$')}{row.get('price',0):.0f} {row.get('currency','')}"
            score    = row.get('hybrid', 0)
            link     = str(row.get('product_link', ''))
            has_link = link and link not in ('nan', 'None', '')
            link_html = (
                f'<a href="{link}" target="_blank" style="color:#9A6B4B;font-size:12px;'
                f'text-decoration:none;border-bottom:1px solid #D4B89A">view →</a>'
                if has_link else ''
            )
            card = (
                '<div style="display:flex;align-items:center;gap:14px;padding:10px 0;border-bottom:1px solid #F5F0EB">'
                f'<div style="width:38px;height:38px;border-radius:50%;background:#{shade};border:1px solid #E0D8D0;flex-shrink:0"></div>'
                '<div style="flex:1;min-width:0">'
                f'<div style="font-size:14px;font-weight:500;color:#3D2B2B;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">#{rank} {brand} — {name}</div>'
                f'<div style="font-size:12px;color:#9A8880">{price}</div>'
                '</div>'
                '<div style="text-align:right;flex-shrink:0">'
                f'<div style="font-size:13px;font-weight:500;color:#7A5C10">{score*100:.0f}%</div>'
                '<div style="width:60px;height:3px;background:#EDE4DC;border-radius:2px;margin:4px 0">'
                f'<div style="width:{score*100:.0f}%;height:100%;background:linear-gradient(90deg,#7A5C10,#C4A052);border-radius:2px"></div>'
                '</div>'
                f'{link_html}'
                '</div>'
                '</div>'
            )
            lines.append(card)
            rank += 1
    lines.append('</div>')

    export_cols = ['brand','name','product_type','price','price_sign','currency','product_link','best_shade','hybrid']
    export_df = combined_df[[c for c in export_cols if c in combined_df.columns]].copy()
    export_df.columns = [c.replace('_',' ').title() for c in export_df.columns]
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix='.csv')
    export_df.to_csv(tmp.name, index=False)
    tmp.close()

    return ''.join(lines), gr.update(visible=True, value=tmp.name)


# ── Theme ──────────────────────────────────────────────────────────────────
theme = gr.themes.Base(
    primary_hue=gr.themes.colors.stone,
    secondary_hue=gr.themes.colors.stone,
    neutral_hue=gr.themes.colors.stone,
    font=[gr.themes.GoogleFont('DM Sans'), 'sans-serif'],
    font_mono=[gr.themes.GoogleFont('DM Mono'), 'monospace'],
).set(
    body_background_fill='#F5F0EB',
    body_text_color='#3D2B2B',
    block_background_fill='#FDFAF7',
    block_border_color='#E8DDD5',
    block_label_background_fill='#F5F0EB',
    block_label_text_color='#9A8880',
    button_primary_background_fill='#7A5C10',
    button_primary_background_fill_hover='#5A3E08',
    button_primary_text_color='#FFFFFF',
    input_background_fill='#FDFAF7',
    input_border_color='#E8DDD5',
    border_color_primary='#E8DDD5',
    shadow_drop='0 2px 12px rgba(28,22,18,0.08)',
    block_radius='12px',
    input_radius='8px',
    button_large_radius='50px',
)

css = """
.gradio-container { max-width: 1000px !important; margin: 0 auto !important; }
.tab-nav { border-bottom: 1px solid #E8DDD5 !important; }
.tab-nav button { font-size: 14px !important; font-weight: 500 !important; color: #9A8880 !important; padding: 12px 20px !important; }
.tab-nav button.selected { color: #3D2B2B !important; border-bottom: 2px solid #7A5C10 !important; }
h1 { font-family: 'Georgia', serif !important; font-weight: 400 !important; font-size: 36px !important; color: #3D2B2B !important; }
.prose p { color: #9A8880 !important; font-size: 14px !important; }
footer { display: none !important; }
"""

# ── App ────────────────────────────────────────────────────────────────────
with gr.Blocks(theme=theme, css=css, title="Anita's Makeup Recommender") as demo:

    gr.Markdown("# Anita's Makeup Recommender")

    with gr.Tabs() as tabs:

        # ── Tab 1 ──────────────────────────────────────────────────────────
        with gr.TabItem('📷  Step 1 — Analyze Photo', id=0):
            gr.Markdown('Upload a clear, well-lit selfie. SAM3 will segment your face and detect your skin, lip, nose, eyebrows and eye colors.')

            with gr.Row():
                with gr.Column(scale=1):
                    photo_input = gr.Image(label='Your photo', type='numpy', height=340)
                    analyze_btn = gr.Button('Analyze photo →', variant='primary', size='lg')
                with gr.Column(scale=1):
                    overlay_out   = gr.Image(label='Segmentation overlay', height=340)
                    analysis_html = gr.HTML('<p style="color:#9A8880;font-style:italic;padding:16px 0">Results will appear here after analysis.</p>')

            eye_picker_html = gr.HTML('', visible=False)

            with gr.Row(visible=False) as go_btn_row:
                go_btn = gr.Button('→ Continue to Step 2 — Get Recommendations', variant='primary', size='lg')

            with gr.Row():
                skin_out = gr.Textbox(label='Skin hex', visible=False)
                lip_out  = gr.Textbox(label='Lip hex',  visible=False)
                eye_out  = gr.Textbox(label='Eye hex',  visible=False)
                look_out = gr.Textbox(label='Look',     visible=False)
                monk_out = gr.Number(label='Monk',      visible=False, value=4)

            analyze_btn.click(
                run_analysis,
                inputs=[photo_input],
                outputs=[overlay_out, analysis_html,
                         skin_out, lip_out, eye_out, look_out, monk_out,
                         eye_picker_html]
            ).then(
                lambda: (gr.update(visible=True), gr.update(visible=True)),
                outputs=[eye_picker_html, go_btn_row]
            )

            go_btn.click(
                lambda: gr.update(selected=1),
                outputs=[tabs]
            )

        # ── Tab 2 ──────────────────────────────────────────────────────────
        with gr.TabItem('💄  Step 2 — Get Recommendations', id=1):

            with gr.Row():
                # ── Left: color profile ────────────────────────────────────
                with gr.Column(scale=1):
                    gr.Markdown('### Color profile')
                    gr.Markdown('*Auto-filled from Step 1*')

                    with gr.Row(equal_height=True):
                        skin_swatch = gr.HTML(make_swatch('C8A07A', 'C8A07A'))
                        skin_in     = gr.Textbox(label='Skin hex', value='C8A07A', max_lines=1, scale=4)

                    with gr.Row(equal_height=True):
                        lip_swatch = gr.HTML(make_swatch('A05450', 'A05450'))
                        lip_in     = gr.Textbox(label='Lip hex', value='A05450', max_lines=1, scale=4)

                    with gr.Row(equal_height=True):
                        eye_swatch = gr.HTML(make_swatch('4D453B', '4D453B'))
                        eye_in     = gr.Textbox(label='Eye hex', value='4D453B', max_lines=1, scale=4)

                    ut_in = gr.Dropdown(label='Undertone', choices=['Any','warm','cool','neutral'], value='warm')

                # ── Right: look, products, monk ────────────────────────────
                with gr.Column(scale=1):
                    gr.Markdown('### Look & products')
                    look_in  = gr.Dropdown(
                        label='Desired look',
                        choices=list(LOOK_LABELS.values()),
                        value='Glam'
                    )
                    types_in = gr.CheckboxGroup(
                        label='Product types',
                        choices=list(TYPE_LABELS.values()),
                        value=['Lipstick','Eyeshadow','Foundation']
                    )

                    gr.HTML("""
                    <div style="margin-top:12px">
                      <p style="font-weight:600;color:#3D2B2B;font-size:14px;margin-bottom:8px">Monk skin tone</p>
                      <div style="display:flex;gap:5px;margin-bottom:6px">
                        <div style="text-align:center"><div style="width:30px;height:30px;border-radius:50%;background:#f6ede4;border:1.5px solid #E0D8D0"></div><div style="font-size:10px;color:#9A8880;margin-top:2px">1</div></div>
                        <div style="text-align:center"><div style="width:30px;height:30px;border-radius:50%;background:#f3e7db;border:1.5px solid #E0D8D0"></div><div style="font-size:10px;color:#9A8880;margin-top:2px">2</div></div>
                        <div style="text-align:center"><div style="width:30px;height:30px;border-radius:50%;background:#f7ead0;border:1.5px solid #E0D8D0"></div><div style="font-size:10px;color:#9A8880;margin-top:2px">3</div></div>
                        <div style="text-align:center"><div style="width:30px;height:30px;border-radius:50%;background:#eadaba;border:1.5px solid #E0D8D0"></div><div style="font-size:10px;color:#9A8880;margin-top:2px">4</div></div>
                        <div style="text-align:center"><div style="width:30px;height:30px;border-radius:50%;background:#d7bd96;border:1.5px solid #E0D8D0"></div><div style="font-size:10px;color:#9A8880;margin-top:2px">5</div></div>
                        <div style="text-align:center"><div style="width:30px;height:30px;border-radius:50%;background:#a07850;border:1.5px solid #E0D8D0"></div><div style="font-size:10px;color:#9A8880;margin-top:2px">6</div></div>
                        <div style="text-align:center"><div style="width:30px;height:30px;border-radius:50%;background:#825c43;border:1.5px solid #E0D8D0"></div><div style="font-size:10px;color:#9A8880;margin-top:2px">7</div></div>
                        <div style="text-align:center"><div style="width:30px;height:30px;border-radius:50%;background:#604134;border:1.5px solid #E0D8D0"></div><div style="font-size:10px;color:#9A8880;margin-top:2px">8</div></div>
                        <div style="text-align:center"><div style="width:30px;height:30px;border-radius:50%;background:#3a312a;border:1.5px solid #E0D8D0"></div><div style="font-size:10px;color:#9A8880;margin-top:2px">9</div></div>
                        <div style="text-align:center"><div style="width:30px;height:30px;border-radius:50%;background:#292420;border:1.5px solid #E0D8D0"></div><div style="font-size:10px;color:#9A8880;margin-top:2px">10</div></div>
                      </div>
                    </div>
                    """)

                    monk_in = gr.Slider(label='Level (1–10)', minimum=1, maximum=10, step=1, value=4)

            gr.Markdown('### Per-category settings')
            gr.Markdown('*Select product types above to configure each one*')

            price_inputs = {}
            n_inputs     = {}
            type_rows    = {}

            for type_key, type_label in TYPE_LABELS.items():
                with gr.Row(visible=False) as row:
                    gr.HTML(f'<p style="margin:auto 0;font-weight:600;color:#3D2B2B;min-width:90px">{type_label}</p>')
                    n_inputs[type_key] = gr.Slider(
                        label='# results', minimum=1, maximum=10, step=1, value=3, scale=2
                    )
                    price_inputs[type_key] = (
                        gr.Number(label='Min $', value=0, scale=1),
                        gr.Number(label='Max $', value=0, info='0 = no limit', scale=1),
                    )
                type_rows[type_key] = row

            def update_rows(selected_types):
                return [
                    gr.update(visible=(TYPE_LABELS[k] in selected_types))
                    for k in TYPE_LABELS
                ]

            types_in.change(
                update_rows,
                inputs=[types_in],
                outputs=list(type_rows.values())
            )

            rec_btn      = gr.Button('Get recommendations →', variant='primary', size='lg')
            rec_html     = gr.HTML('<p style="color:#9A8880;font-style:italic;padding:16px 0">Results will appear here.</p>')
            download_btn = gr.DownloadButton(label='⬇ Download recommendations', visible=False)

            all_inputs = [skin_in, lip_in, eye_in, look_in, types_in, ut_in, monk_in]
            for type_key in TYPE_LABELS:
                pmin, pmax = price_inputs[type_key]
                all_inputs += [pmin, pmax]
            for type_key in TYPE_LABELS:
                all_inputs.append(n_inputs[type_key])

            rec_btn.click(
                run_recommend,
                inputs=all_inputs,
                outputs=[rec_html, download_btn]
            )

            # Auto-fill from Tab 1 + update swatches
            skin_out.change(lambda x: (x, make_swatch(x,'C8A07A')), skin_out, [skin_in, skin_swatch])
            lip_out.change(lambda x:  (x, make_swatch(x,'A05450')), lip_out,  [lip_in,  lip_swatch])
            eye_out.change(lambda x:  (x, make_swatch(x,'4D453B')), eye_out,  [eye_in,  eye_swatch])
            monk_out.change(lambda x: x, monk_out, monk_in)

            # Live swatch update when user types manually
            skin_in.change(lambda x: make_swatch(x,'C8A07A'), skin_in, skin_swatch)
            lip_in.change(lambda x:  make_swatch(x,'A05450'), lip_in,  lip_swatch)
            eye_in.change(lambda x:  make_swatch(x,'4D453B'), eye_in,  eye_swatch)

demo.launch(share=True, debug=False)